version: "3"
services:

  selenium_hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  firefox:
      image: selenium/node-firefox
      environment:
        - HUB_PORT_4444_TCP_ADDR=selenium_hub
        - HUB_PORT_4444_TCP_PORT=4444
      ports:
        - "5555"
      depends_on:
        - selenium_hub

  chrome:
      image: selenium/node-chrome
      environment:
        - HUB_PORT_4444_TCP_ADDR=selenium_hub
        - HUB_PORT_4444_TCP_PORT=4444
      ports:
        - "5555"
      depends_on:
        - selenium_hub

networks:
  default:
