version: "3"
services:

  selenium_hub:
    image: selenium/hub
    environment:
      - GRID_TIMEOUT=180000
      - GRID_BROWSER_TIMEOUT=0
    ports:
      - "4444:4444"

  firefox:
    image: selenium/node-firefox
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5555"
    depends_on:
      - selenium_hub
    volumes:
      - /dev/shm:/dev/shm

  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5555"
    depends_on:
      - selenium_hub
    volumes:
      - /dev/shm:/dev/shm

networks:
  default:
